version: '3.0'

services:
  backend:
    container_name: nest
    build:
      context: .
    env_file:
      - backend/.development.env
    volumes:
      - .:/app
      - /backend/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - /backend/.development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  frontend:
    container_name: react
    build:
      context: .
    depends_on:
      - backend
      - postgres
    restart: always
    command: npm run start
    ports:
      - 3000:3000

volumes:
  pgdata: